- name: Donwload zabbix deb
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
    dest: /tmp/

- name: Install zabbix
  ansible.builtin.apt:
    deb: /tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb
    state: present

- name: Install zabbix packages
  apt:
    name: ['mysql-server', 'zabbix-proxy-mysql', 'zabbix-sql-scripts']
    state: present
    update_cache: true